[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "packaging",

    "numpy>=1.22.4",
    "torch-mlir>=20221021.633",
    "iree-compiler",
    "iree-runtime",
]
build-backend = "setuptools.build_meta"
